install vim --override-system-vi
install coreutils
install findutils
install rbenv
install ruby-build
install zsh
install pngquant
install imagemagick
install openvpn
install ack
install wget
install bcrypt
install xz
install node
install autojump
install nginx
install sqlite
install postgresql
install redis
install git-flow
install tmux
install mongodb
install mackup
install tor
install go
install mpd
